[package]
name = "witness-lwk"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
live-lwk = ["dep:lwk_wollet"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
witness-core.workspace = true
lwk_wollet = { version = "0.17", features = ["esplora", "amp0", "amp2"], optional = true }
