[package]
name = "witness-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "witness"
path = "src/main.rs"

[features]
live-lwk = ["witness-lwk/live-lwk"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
dotenvy = "0.15"
serde.workspace = true
serde_json.workspace = true
witness-core.workspace = true
witness-lwk.workspace = true
